### ISSUE TITLE
CI Testing and Code Coverage

### ISSUE THREAD

**Issue by banesullivan** [akaszynski/vtki#28]
I see the Travis script uses `pytest-cov`, does this test runner report code coverage?

Do you, @akaszynski, by chance have the coverage reported to a service like [codecov](https://codecov.io)?

This would be a major help for me to figure out what still needs testing as I've added quite a bit of untested code in the last 24 hours

**Comment by akaszynski** [comment]
I've yet to take the time to get travis-ci talking with codecov.  As much as I don't want to, I have to test it locally as it can't be 100% tested without X11.  If I were you, I'd test for coverage locally with:
```
pytest --cov vtki --cov-report html
```
I'll look into adding support for a coverage report.  BTW, thanks for adding the tests!

**Comment by banesullivan** [comment]
Ah, awesome! I’ll use that to get a local coverage report

On the note of CI testing... you can set up Travis to use OSX instead of Linux... I wonder if it’s possible to use X11 on those builds... (my intuition tells me it’s not possible)

**Comment by akaszynski** [comment]
I'd actually like to get OSX running on Travis, I've had an issue in the past where it failed for Mac and I wasn't able to reproduce it on my end.  Ended up getting it working, but it took some guessing.  As for X11, I run into the same issue when testing remotely on Windows.  Unless there's a display to connect to, I can't test the plotting, even when using off-screen plotting.  Maybe there's a way to work around it...

**Comment by banesullivan** [comment]
So I've been toying around a bit with `xvfb` on the `citesting` branch to see if there might be a way to connect to a virtual display. [This article](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI), [this article](https://electronjs.org/docs/tutorial/testing-on-headless-ci), and [this Python project](https://pypi.org/project/xvfbwrapper/) seem like what we'd need for testing on the Linux version of Travis.

Is there a way to tell pytest to execute this workflow whenever a test requires X11 but isn't available?:

```py
from xvfbwrapper import Xvfb

vdisplay = Xvfb()
vdisplay.start()

# launch stuff inside
# virtual display here.

vdisplay.stop()
```

**Comment by banesullivan** [comment]
I think I figured it out! See #31
