### ISSUE TITLE
Creating a Conda recipe

### ISSUE THREAD

**Issue by banesullivan** [akaszynski/vtki#32]
I propose we get a conda build recipe up for `vtki` because of the headaches that Windows installations bring:

I've been running into trouble making `vtki` a dependency of my project [PVGeo](https://github.com/OpenGeoVis/PVGeo). When I run the Windows CI testing (AppVeyor) for the environment:

```txt
Environment: PYTHON_VERSION=3.6, CONDA=C:\Miniconda36; Platform: x86
```

The `setup.py` script for `vtki` tries to add VTK to the dependencies but it is unavailable for that build from pip, only from conda. 

```txt
Collecting vtk (from vtki>=0.13.0->-r requirements.txt (line 9))
Could not find a version that satisfies the requirement vtk (from vtki>=0.13.0->-r requirements.txt (line 9)) (from versions: )
No matching distribution found for vtk (from vtki>=0.13.0->-r requirements.txt (line 9))
```

Perhaps we should change the setup.py script to always warn on windows? Or better yet, do you (@akaszynski) know how to setup conda build recipes?

I haven't been able to figure this out for myself but I beginning to see that conda recipes will be a necessity for projects depending on VTK.

**Comment by akaszynski** [comment]
It’s strange that pip doesn’t see vtk.  Was it installed already using pip or conda?  You might try installing it first as a requirement before testing PVGeo. 

I can look into making a conda recipe for vtki, but I’m on vacation right now and it might take a bit before I have time to look at it.

Appveyor worked for me for vtki.  Try looking at my appveyor.ymland see if you can try implementing that on your end

**Comment by akaszynski** [comment]
Still need a conda recipe?

**Comment by banesullivan** [comment]
I think it would be beneficial to make installing vtki easier. Plus I need to learn how to set them up

**Comment by banesullivan** [comment]
The issue I'm running into is on Windows x86, vtki is only tested on x64. If I manually install vtki using pip and vtk using conda then all is good. But if I try a simple `pip install vtki`, pip cannot recognize that vtk is already installed and pip doesn't find a suitable version. This is shown in an AppVeyor build of PVGeo where I am trying to add `vtki` as a requirement. The full build log is [here](https://ci.appveyor.com/project/banesullivan/pvgeo/builds/21478560/job/u93reh7jd1kytep9#L261)

```txt
$ pip install vtki
 Collecting vtki
 Downloading https://files.pythonhosted.org/packages/f6/a7/c723412e547b7bec79162a9341f450e2c02e764da33da83f5ac0bf5fea92/vtki-0.14.0.tar.gz (204kB)
 Requirement already satisfied: numpy in c:\miniconda36\lib\site-packages (from vtki) (1.15.4)
 Collecting imageio (from vtki)
 Downloading https://files.pythonhosted.org/packages/28/b4/cbb592964dfd71a9de6a5b08f882fd334fb99ae09ddc82081dbb2f718c81/imageio-2.4.1.tar.gz (3.3MB)
 Collecting vtk (from vtki)
 Could not find a version that satisfies the requirement vtk (from vtki) (from versions: )
 No matching distribution found for vtk (from vtki)
```

I'm wondering if I can just change that vtki will only add vtk to its requirements if Windows is x64 or on mac/linux

**Comment by akaszynski** [comment]
The maintainers of vtk put out wheels for most Python/OS combinations, but they're missing wheels for Windows 32 bit and Python 2.7 for Win64, which is why it can't be installed using pip.  They do, however, maintain conda recipes at [vtk-anaconda](https://anaconda.org/anaconda/vtk).  I'm going to add a note in the setup file about this and inform the user that if they're using Windows, they might try using conda.

**Comment by banesullivan** [comment]
See #127
