### ISSUE TITLE
Is it possible to clear the added mesh?

### ISSUE THREAD

**Issue by dangit6413** [akaszynski/vtki#33]
Hello,
Is there any methods to clear the plotted mesh?
Once I call "add_mesh" method, I can't clear the mesh plotting.
I tried to call add_mesh method with dummy grid object but didn't help.

**Comment by banesullivan** [comment]
Hi @dangit6413, at the moment this doesn't appear to be possible (@akaszynski would know for sure) but I don't think it would be too difficult to implement. As I was exploring this I realized an issue on v0.14.0 that will definitely prevent this from working.

Could you provide some sample code of how you might expect to clear the mesh? Perhaps use one of the examples like:

```py
import vtki
from vtki import examples

dataset = examples.load_uniform()

p = vtki.Plotter(notebook=False)
p.add_mesh(dataset)
p.plot(in_background=True)

# TODO: how would we clear the mesh/distinguish it from other datasets being plotted?
```

**Comment by dangit6413** [comment]
Hi, @banesullivan 
Nothing special code I have.
Just in the official  example of vtki in link below. 
https://vtkinterface.readthedocs.io/en/latest/qt_plotting.html

I just want to call clear_mesh method after add sphere.

**Comment by akaszynski** [comment]
Added new ``clear`` method.  See [Clearing a Mesh or the Entire Plot](https://vtkinterface.readthedocs.io/en/latest/examples.html#clearing-a-mesh-or-the-entire-plot)
