### ISSUE TITLE
Color bar not rendering on Windows OS

### ISSUE THREAD

**Issue by banesullivan** [akaszynski/vtki#48]
I have a Windows VM that I've been using to test a few things and I noticed I cannot get the color bars to render:

```py
import vtki
from vtki import examples

dataset = examples.load_uniform()
dataset.plot(screenshot='foo-windows.png')
```

![foo-windows](https://user-images.githubusercontent.com/22067021/51229824-fca49780-191a-11e9-8ffe-d852787e404e.png)

### Notes

- Python 3.6
- Architecture: 64bit WindowsPE
- VTK Version: 8.1.2

**Comment by banesullivan** [comment]
*NOTE:* I'm thinking this might be because I am on a Virtual Machine

**Comment by akaszynski** [comment]
I've had similar problems when using VMs with VTK.  It's an issue on Virtual Box but not vmware.  I'd ignore this.

**Comment by banesullivan** [comment]
Just an FYI: I'm using vmware right now with an Ubuntu VM and this issue persists:

<img width="912" alt="Screen Shot 2019-07-26 at 1 02 40 PM" src="https://user-images.githubusercontent.com/22067021/61975167-a8ebc880-afa5-11e9-9278-4cc438adf779.png">

**Comment by Wying301** [comment]
> Just an FYI: I'm using vmware right now with an Ubuntu VM and this issue persists:
> 
> <img alt="Screen Shot 2019-07-26 at 1 02 40 PM" width="912" src="https://user-images.githubusercontent.com/22067021/61975167-a8ebc880-afa5-11e9-9278-4cc438adf779.png">

Hi, I met similar problem when using VMware, have you ever solved this problem?

**Comment by banesullivan** [comment]
I believe this is a graphics issue with VMWare that I don't know where to begin addressing.
