### ISSUE TITLE
Remove outdated PyPI deployment

### ISSUE THREAD

**Issue by banesullivan** [akaszynski/vtki#60]
@akaszynski, can you remove the [old PyPI deployment](https://pypi.org/project/vtkInterface/) to avoid confusion from new users

Note, the only project on PyPI that appears to have a dependency to the old `vtkInterface` is [tetgen](https://pypi.org/project/tetgen/)

**Comment by akaszynski** [comment]
I wanted to leave up the old module until I was satisfied with the state of vtki, but I think we're ready now.  Once I refactor [tetgen](https://pypi.org/project/tetgen/), I'll delete it.

**Comment by akaszynski** [comment]
Removed,  both [tetgen](https://pypi.org/project/tetgen/) and [pymeshfix](https://pypi.org/project/pymeshfix/) now use ``vtki``.
