### ISSUE TITLE
Area and volume for each mesh cell

### ISSUE THREAD

**Issue by byba1990** [akaszynski/vtki#71]
Dear Alex,

it is possible to get the area for each cell of a cutting plane, or volume for each cell of a mesh? In particular, I want to get the average for a value over surface or volume.
Thank you for your time.
Regards,

Christian

**Comment by banesullivan** [comment]
There are a few ways you could calculate cell areas (2D) / volumes (3D) that depend on the data type. What kind of `vtki` mesh object are you using for the 3D volume?

For computing triangulated cell areas:

```py
import vtki
from vtki import examples

data = examples.load_airplane()

def compute_area(mesh):
    import vtk
    alg = vtk.vtkMeshQuality()
    alg.SetInputDataObject(mesh)
    alg.SetTriangleQualityMeasureToArea()
    alg.Update()
    return vtki.wrap(alg.GetOutputDataObject(0))

foo = compute_area(data)

foo.plot()

```

![download](https://user-images.githubusercontent.com/22067021/52361561-c5964300-29fb-11e9-9de0-188676edc422.png)


And for volumes:

**Comment by banesullivan** [comment]
FYI, I've been meaning to implement a `Common` filter for `vtki` that behaves just like [ParaView's `CellSize` filter](https://kitware.github.io/paraview-docs/latest/python/paraview.simple.CellSize.html)

**Comment by banesullivan** [comment]
Above code snippet provides an immediate solution and MR #72 adds this filter to all `vtki` datasets

**Comment by byba1990** [comment]
Ok, it works! Thank you very much for your help!
Regards,

Christian
