### ISSUE TITLE
Plotter.screenshot return options

### ISSUE THREAD

**Issue by banesullivan** [akaszynski/vtki#81]
Can we change the default behavior of what is returned on the `Plotter.screenshot` call when a filename is passed? Perhaps add an argument `return_image=None` that can be used to get the NumPy array of the image if a user wants it after saving the image?

It makes notebooks a bit messy in its current implementation:

<img width="924" alt="screen shot 2019-02-11 at 2 16 31 pm" src="https://user-images.githubusercontent.com/22067021/52594096-e3064b00-2e07-11e9-8f36-7c7b45d8de56.png">

**Comment by akaszynski** [comment]
I don't generally use the raw arrays, so making the default return ``None`` would be fine.

**Comment by banesullivan** [comment]
Implemented in 97761e2
