### ISSUE TITLE
enable math-tex for labels

### ISSUE THREAD

**Issue by banesullivan** [akaszynski/vtki#83]
I know it is somehow possible to use math-tex / LaTeX math formatting for labels in VTK, but how can we enable it in `vtki`? For example:

```py
plotter.add_bounds_axes(xlabel='$F^2$')

plotter.add_mesh(data, stitle='$stuff^2$')
```

**Comment by akaszynski** [comment]
Looks like paraview does it using ``matplotlib`` [Equation Rendering](https://www.paraview.org/Wiki/ParaView/Equation_Rendering).  It's already an optional requirement, and I can implement a module level function for rendering text.

**Comment by banesullivan** [comment]
Awesome, thanks @akaszynski!

**Comment by akaszynski** [comment]
Opened an issue with ``Kitware`` [https://gitlab.kitware.com/vtk/vtk/issues/17528](Issue #17528).

They didn't compile the ``vtk`` wheels with mathtext support as matplotlib might have conflicted with Python somehow.  I can get halfway there, but it's unclear how to take a vtkImageData and have it replace a text actor or text property.

**Comment by banesullivan** [comment]
Hmm, if you have the latest ParaView installed, you could activate a Python 2.7 environment and edit your path to point to ParaView's local VTK Python package to test/debug.

```py
import sys
sys.path.insert(0, '/Path/to/ParaView/contents/bin/site-packages/or/something/')
import vtk
```

```

**Comment by akaszynski** [comment]
Still working on this, but I don't think this will be something we can solve on our end.  It's possible to render equations and load the resulting png into an actor, but getting the text rendered in the same location as the original label would be a nightmare.  It would mean removing the existing label and property and then adding in the equation label by replacing the existing text, which would be quite difficult based on my dive into their source.

I've suggested that future ``vtk`` wheels be built with equation rendering enabled.  If this isn't possible, can make another attempt trying to render using ``matplotlib``

**Comment by banesullivan** [comment]
If VTK were built with equation rendering enabled, rendering mathtex would be as simple as passing the latex string to the label (`p.add_bounds_axes(xlabel='$\frac{1}{x}$')`), correct?

If so, I propose we close this issue and lobby VTK to compile the upcoming 8.2.0 Python release: https://discourse.vtk.org/t/vtk-8-2-0-come-and-get-it/174

**Comment by banesullivan** [comment]
Or perhaps the conda feedstock would be the appropriate place to have VTK built with equation rendering and a `matplotlib` dependency: https://github.com/conda-forge/vtk-feedstock

**Comment by akaszynski** [comment]
It would have to be by VTK as they're going to be the ones to build the wheel and wheels are more universal than conda.  Most linux users just use the python included with their distro.

**Comment by akaszynski** [comment]
Provided they can compile it, it would result in automatic rendering to mathtex for every available text label.  I'll close this and consider reopening it if they can't compile the wheel with mathtex support.
