### ISSUE TITLE
Input fields for Qt axes scaling dialog

### ISSUE THREAD

**Issue by banesullivan** [akaszynski/vtki#96]
Could we add input text (float) fields next to the sliders on the Qt scale axes dialog?

<img width="499" alt="screen shot 2019-02-18 at 12 24 25 pm" src="https://user-images.githubusercontent.com/22067021/52972476-43513b80-3378-11e9-97d4-f474581e0c0f.png">

It's currently quite difficult to achieve desired scales with the Qt dialog. It might look something like the `vtki.ScaledPlotter` IPython widgets:

<img width="483" alt="screen shot 2019-02-18 at 12 27 01 pm" src="https://user-images.githubusercontent.com/22067021/52972554-83182300-3378-11e9-8242-35880a601078.png">

**Comment by akaszynski** [comment]
Can do.  I’ll add tests as well.

**Comment by akaszynski** [comment]
Added in PR #101.

**Comment by banesullivan** [comment]
This is awesome!! Thanks!
