### ISSUE TITLE
Add website link and topics on repository page

### ISSUE THREAD

**Issue by banesullivan** [akaszynski/vtki#98]
We should add *topics* and a link to the docs (http://docs.vtki.org/) in the repository header information. Currently, the header looks like:

<img width="1003" alt="screen shot 2019-02-18 at 3 46 48 pm" src="https://user-images.githubusercontent.com/22067021/52979785-6be72e80-3394-11e9-8fb8-7b0a5f54c43e.png">

We should add *topics* to help people discover `vtki`. Possible tags include:

- 3D
- visualization
- open-science
- vtk
- python

Check out https://github.com/topics for more info

For example, PVGeo has *topics* and a link:

<img width="1014" alt="screen shot 2019-02-18 at 3 44 37 pm" src="https://user-images.githubusercontent.com/22067021/52979735-2f1b3780-3394-11e9-8873-6491009e624a.png">

**Comment by akaszynski** [comment]
Done.  Please let me know if you have any other suggestions for topics.
